# Generated by Django 4.2.1 on 2023-06-05 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dlName', models.CharField(max_length=50)),
                ('done', models.BooleanField()),
                ('dateTurnedIn', models.CharField(max_length=10)),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('number', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('galv', models.IntegerField()),
                ('ss', models.IntegerField()),
                ('blackIron', models.IntegerField()),
                ('pl', models.IntegerField()),
                ('alum', models.IntegerField()),
                ('dl', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weight', to='jobdata.download')),
            ],
        ),
        migrations.AddField(
            model_name='download',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='jobdata.job'),
        ),
    ]
