# Generated by Django 4.2.1 on 2023-07-06 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobdata', '0003_download_datedue'),
    ]

    operations = [
        migrations.AddField(
            model_name='download',
            name='cutOut',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='download',
            name='duct',
            field=models.IntegerField(default=42),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='download',
            name='fittings',
            field=models.IntegerField(default=23),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='download',
            name='receivedBy',
            field=models.CharField(default='REJ', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='download',
            name='weight',
            field=models.IntegerField(default=565),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='download',
            name='dateDue',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='download',
            name='dateTurnedIn',
            field=models.CharField(max_length=40),
        ),
        migrations.DeleteModel(
            name='Weight',
        ),
    ]
